name: Build & Push image when main.go changes
on:
  push:
    paths: [ 'main.go' ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ➜ 1) fabriquer le nom d’image en minuscules
      - name: Compute image name (lower‑case)
        id: vars
        run: |
          echo "image=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ➜ 2) construire & pousser avec le nom en minuscules
      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max